### ISSUE TITLE
[CLI] Hide backend logs on error

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1015]
**Version:** main
**UI:** dev-1497e86
**Commit ID:** 7346fa3e2f32c2e7a19d3454f50e7842a11cfe1b
**Env:** AWS EC2 Ubuntu 22.04 amd64

The CLI command currently prints too many backend logs when an error occurs.

```
root@ip-192-168-1-101:~/.seal# seal -v
seal version main (7346fa3e2f32c2e7a19d3454f50e7842a11cfe1b)
```

```
root@ip-192-168-1-101:~/.seal# seal config setup --project-name pro2
2023-08-04T09:33:25.386Z	D	Error Stack: goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
main.Run.func1()
	github.com/seal-io/seal/cmd/cli/main.go:32 +0x46
panic({0x962c60, 0xc0001c7180})
	runtime/panic.go:884 +0x212
main.NewConfigCmd.func2(0xc0001c5200?, {0x9f9d5f?, 0x2?, 0x2?})
	github.com/seal-io/seal/cmd/cli/command.go:108 +0x127
github.com/spf13/cobra.(*Command).execute(0xc0001c5200, {0xc000035040, 0x2, 0x2})
	github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001c4c00)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
main.Run()
	github.com/seal-io/seal/cmd/cli/main.go:55 +0xee
main.main()
	github.com/seal-io/seal/cmd/cli/main.go:23 +0x77

error while execute: endpoint is required
```

```
root@ip-192-168-1-101:~/.seal# seal config setup -s https://xxx --project-name pro2 --token xxx
2023-08-04T09:35:39.481Z	D	Error Stack: goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
main.Run.func1()
	github.com/seal-io/seal/cmd/cli/main.go:32 +0x46
panic({0x98fa60, 0xc00036ac30})
	runtime/panic.go:884 +0x212
main.NewConfigCmd.func2(0xc0001c5200?, {0x9f9d5f?, 0x6?, 0x6?})
	github.com/seal-io/seal/cmd/cli/command.go:108 +0x127
github.com/spf13/cobra.(*Command).execute(0xc0001c5200, {0xc000068d80, 0x6, 0x6})
	github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001c4c00)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
main.Run()
	github.com/seal-io/seal/cmd/cli/main.go:55 +0xee
main.main()
	github.com/seal-io/seal/cmd/cli/main.go:23 +0x77

error while execute: Get "https://xxx/v1/projects?query=pro2": x509: certificate signed by unknown authority
```

**Expected Results:**

```
root@ip-192-168-1-101:~/.seal# seal config setup --project-name pro2
error while execute: endpoint is required
```

```
root@ip-192-168-1-101:~/.seal# seal config setup -s https://xxx --project-name pro2 --token xxx
error while execute: Get "https://xxx/v1/projects?query=pro2": x509: certificate signed by unknown authority
```

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version:  main 2314b9d4571c3b6b341dee7ed630a5ffc5793dfe
- UI version: dev-0835269

**Result**
When enter 'Ctrl+C' to interrupt command, it also returns the backend logs.
```
 ~/.walrus/ wa config setup
? Server:  https://192.168.50.182:4433
? Token:  ***********************************************************************************************************************************
? Insecure:  No
? Project:  (default)
2023-08-22T15:33:22.187+0800	D	Error Stack: goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x64
main.Run.func1()
	github.com/seal-io/walrus/cmd/cli/main.go:32 +0x3c
panic({0x100b24880, 0x14000110d60})
	runtime/panic.go:884 +0x204
main.NewConfigCmd.func2(0x140001fd200?, {0x1009d2c10?, 0x0?, 0x0?})
	github.com/seal-io/walrus/cmd/cli/command.go:101 +0x114
github.com/spf13/cobra.(*Command).execute(0x140001fd200, {0x100f94048, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:944 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x140001fcc00)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
main.Run()
	github.com/seal-io/walrus/cmd/cli/main.go:55 +0x100
main.main()
	github.com/seal-io/walrus/cmd/cli/main.go:23 +0x70

interrupt
```

**Comment by shanewxy** [comment]
**Environment**
- Walrus version: v0.4.0-rc2 af772a7ae049670658fdb2d2249cfde51277db8e
- UI version: v0.4.0-rc2

**Test Result**: pass
```
./cli config setup
? Server:  https://192.168.50.78:443
? Token:  ***********************************************************************************************************************************
? Insecure:  No
? Project:  default
? Environment:  
interrupt
```
