### ISSUE TITLE
Failed to generate schema using CLI: runtime error: index out of range [n] with length n

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#1788]
**Describe the bug**

**Steps to reproduce**
1. git clone git@github.com:walrus-catalog/terraform-kubernetes-containerservice.git
2. Remove the schema.yaml file.
3. Execute command `walrus schema generate --dir terraform-kubernetes-containerservice -d`

**Result**

```
 ~/Documents/git-test/ w schema generate --dir terraform-kubernetes-containerservice -d
2023-12-29T15:09:33.917+0800	D	Error Stack: goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x64
main.Run.func1()
	github.com/seal-io/walrus/cmd/cli/main.go:29 +0x3c
panic({0x103b4e6a0, 0x140004cec90})
	runtime/panic.go:884 +0x204
github.com/seal-io/walrus/pkg/cli/schema.FormattedOpenAPI({0x14000133710})
	github.com/seal-io/walrus/pkg/cli/schema/format.go:109 +0x8dc
github.com/seal-io/walrus/pkg/cli/schema.Generate({{0x16d26afd5?, 0x0?}})
	github.com/seal-io/walrus/pkg/cli/schema/generate.go:38 +0xa4
github.com/seal-io/walrus/pkg/cli/cmd.NewSchemaCmd.func2(0x1400003d800?, {0x10374e4aa?, 0x3?, 0x3?})
	github.com/seal-io/walrus/pkg/cli/cmd/schema.go:29 +0x28
github.com/spf13/cobra.(*Command).execute(0x1400003d800, {0x1400082e9c0, 0x3, 0x3})
	github.com/spf13/cobra@v1.7.0/command.go:944 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x1400003c900)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
main.Run()
	github.com/seal-io/walrus/cmd/cli/main.go:52 +0x100
main.main()
	github.com/seal-io/walrus/cmd/cli/main.go:20 +0x70

runtime error: index out of range [3] with length 3
```

**Expected behavior**

Generate schema successfully.

**Environment**
- Walrus version: 9735afb411c8b8bef83e11d048bb6a93494ac3ff

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main a32da81f4a08410f854d9897f88885b7a5dc63fd

**Test Result:** pass
