### ISSUE TITLE
Unable to set the default project using Walrus CLI in Windows OS

### ISSUE THREAD

**Issue by Finenyaco** [seal-io/walrus#2100]
**Describe the bug**

**Steps to reproduce**

```
> walrus login
? Insecure:  Yes
? Project:  default
? Environment:
cli configuration is invalid: project default not found. You can configure cli by running "walrus login"
```
```
> w project list
 ID                   NAME      CREATED
-------------------- --------- -----------------------------
 498516099676007170   default   2024-01-31T02:32:30.368133Z

> w context switch -p default -d
2024-02-02T11:32:51.817+0800    D       Error Stack: goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x64
main.Run.func1()
        github.com/seal-io/walrus/cmd/cli/main.go:29 +0x3c
panic({0x7ff6ebf0f820?, 0x4000260390?})
        runtime/panic.go:914 +0x218
github.com/seal-io/walrus/pkg/cli/cmd.Context.func2(0x40000c2700?, {0x7ff6ec09291b?, 0x4?, 0x7ff6ec09292b?})
        github.com/seal-io/walrus/pkg/cli/cmd/context.go:59 +0x1b8
github.com/spf13/cobra.(*Command).execute(0x4000326c00, {0x40008a6030, 0x3, 0x3})
        github.com/spf13/cobra@v1.8.0/command.go:987 +0x828
github.com/spf13/cobra.(*Command).ExecuteC(0x4000326600)
        github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.0/command.go:1039
main.Run()
        github.com/seal-io/walrus/cmd/cli/main.go:52 +0xe4
main.main()
        github.com/seal-io/walrus/cmd/cli/main.go:20 +0x6c

cli configuration is invalid: project default not found. You can configure cli by running "walrus login"
```

**Expected behavior**

**Environment**
- Walrus version: 6d95d8394ff034c404eb3eed108a3856bb6fc773

**Additional context**

**Comment by thxCode** [comment]
related #2069

**Comment by Finenyaco** [comment]
**Environment**
- Walrus version: main 5d939ccf90935cc12b8b7cd7d28e5bd255c22df5
- UI version: dev-a712ac5

**Test Result:** pass
